name: rollbar_common
description: Commons package used by the Rollbar Dart and Flutter SDKs for error reporting.
version: 2.0.0
homepage: https://www.rollbar.com
documentation: https://docs.rollbar.com/docs/flutter#dart
repository: https://github.com/rollbar/rollbar-flutter

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: '>=0.13.0 <2.0.0'
  collection: ^1.16.0
  sqlite3: ^1.11.2
  uuid: ^4.1.0
  meta: ^1.7.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.21.0
  build_runner: ^2.2.0
  mockito: ^5.3.0
  pubspec_parse: ^1.2.0
