name: rollbar_dart_example
description: Demonstrates how to use rollbar-dart
version: 2.0.0

publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  logging: ^1.0.2
  rollbar_common:
    path: ../../rollbar_common
  rollbar_dart:
    path: ..

dev_dependencies:
  lints: ^2.0.0
