name: rollbar_dart_example
description: Demonstrates how to use rollbar-dart

publish_to: 'none' 

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  rollbar_dart: any

dependency_overrides:
  rollbar_dart:
    path: ..

dev_dependencies:
  pedantic: '>=1.9.2 <1.12.0'
