name: rollbar_flutter
description: Connect your Flutter applications to Rollbar for error reporting.
version: 0.1.0-beta
homepage: https://www.rollbar.com
documentation: https://docs.rollbar.com/docs/flutter#flutter
repository: https://github.com/rollbar/rollbar-flutter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  rollbar_dart: ">=0.1.0-beta <0.2.0"
  logging: '>=0.11.4 <1.1.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: '>=1.9.0 <=1.11.0'
  mockito: '>=4.1.0 <=5.0.7'

flutter:
  plugin:
    platforms:
      android:
        package: com.rollbar.flutter
        pluginClass: RollbarFlutterPlugin
      ios:
        pluginClass: RollbarFlutterPlugin
