name: rollbar_dart
description: Connect your Dart applications to Rollbar for error reporting
version: 0.1.0-beta
homepage: https://www.rollbar.com
documentation: https://docs.rollbar.com/docs/flutter#dart
repository: https://github.com/rollbar/rollbar-flutter

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies: 
  http: '>=0.12.2 <0.14.0'
  stack_trace: '>=1.9.5 <1.11.0'

dev_dependencies:
  pedantic: '>=1.9.2 <1.12.0'
  test: ^1.14.4
  mockito: '>=4.1.0 <=5.0.7'
  pubspec_parse: '>=0.1.8 <=1.0.0'
