name: rollbar_dart
description: Connect your Dart applications to Rollbar for error reporting.
version: 1.3.1
homepage: https://www.rollbar.com
documentation: https://docs.rollbar.com/docs/flutter#dart
repository: https://github.com/rollbar/rollbar-flutter

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  http: ^1.1.0
  meta: ^1.7.0
  sqlite3: ^1.7.0
  collection: ^1.16.0
  stack_trace: ^1.10.0
  rollbar_common: ^1.1.0

dependency_overrides:
  rollbar_common:
    path: ../rollbar_common

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  mockito: ^5.2.0
  build_runner: ^2.2.0
  pubspec_parse: ^1.2.0
