name: rollbar_dart
description: Connect your Dart applications to Rollbar for error reporting.
version: 2.0.0
homepage: https://www.rollbar.com
documentation: https://docs.rollbar.com/docs/flutter#dart
repository: https://github.com/rollbar/rollbar-flutter

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: '>=0.13.0 <2.0.0'
  meta: ^1.7.0
  sqlite3: ^2.4.3
  collection: ^1.16.0
  stack_trace: ^1.10.0
  rollbar_common:
    path: ../rollbar_common

dev_dependencies:
  lints: ^4.0.0
  test: ^1.21.0
  mockito: ^5.2.0
  build_runner: ^2.2.0
  pubspec_parse: ^1.2.0
